### ISSUE TITLE
can't read girder item from non-public collection

### ISSUE THREAD

**Issue by curtislisle** [arborworkflows/ArborWebApps#118]

**Comment by jeffbaumes** [comment]
Care to provide a bit more detail :)

**Comment by curtislisle** [comment]
Sorry, my keyboard batteries went out while typing....  Can't read a girder item stored in a non-public collection from phyloTraitMap.  Suspect the authentication code in phyloTraitMap.  The item is listed on in the folder using girder item list, but when we try to retreive the item using Romanesco, an empty return occurs.  Current solution is to copy item to public collection (e.g. Arbor) for use in phyloMap.

**Comment by curtislisle** [comment]
PR issued by Dan to fix this. was using d3.json instead of girder restRequest()
