### ISSUE TITLE
Inputs with the same name in workflows get crossed

### ISSUE THREAD

**Issue by uyedaj** [arborworkflows/ArborWebApps#119]
There are two instances  where this occurs, both within and between workflows.
Within workflows:
In the public Arbor collection the function coleDataPrepV2 has two "tree" elements. Despite providing the second tree in the input, it says that it's absent.

Between workflows:
If I switch between the public Arbor workflows "fitTraitModels" and "coleDataPrepV2", the drop down menu for "Model" gives me the model inputs for the previous module (e.g. the coleDataPrepV2 version should give "lambda, BM, OU, ....", while the fitTraitModels should only give ("BM, OU, EB")).

**Comment by jeffbaumes** [comment]
The first issue should be fixed in Kitware/tangelohub#132. I'm still seeing the second issue.

**Comment by jeffbaumes** [comment]
Second issue should be fixed in https://github.com/Kitware/tangelohub/pull/146. Let me know if you still see issues.
