### ISSUE TITLE
It is possible to have a workflow where the "setup and run" button has no effect

### ISSUE THREAD

**Issue by lukejharmon** [arborworkflows/ArborWebApps#120]
An example is "bob2test" in the Arbor collection. For me, "setup and run" button does nothing. I think this should return an error or something at least...  not sure what is going on.

**Comment by zackgalbreath** [comment]
This particular workflow fails because it requests column names from an internal table.  I believe that this issue is tracked as https://github.com/Kitware/tangelohub/issues/115.

I agree that an error message is appropriate here.

**Comment by zackgalbreath** [comment]
https://github.com/Kitware/tangelohub/pull/140 adds this error message.
