### ISSUE TITLE
Default settings for analyses are not visible when using "Set Up and Run"

### ISSUE THREAD

**Issue by bobthacker** [arborworkflows/ArborWebApps#127]
Where are the default settings for the analyses?

**Comment by jeffbaumes** [comment]
Please try this again. The behavior should be that default values show up in the setup and run dialog upon opening it the first time. If you update settings and run and/or close the dialog then reopen, your custom settings should remain. If you  move to another analysis then back, values will revert back to default values. If you are still seeing issues reopen this and let me know what analysis/input you are seeing unexpected behavior with.

**Comment by jeffbaumes** [comment]
To clarify: some fixes have gone in that may have changed behavior - it does not surprised me that you have seen this in the past.
