### ISSUE TITLE
Where do user uploaded files disappear when refreshing the screen

### ISSUE THREAD

**Issue by bobthacker** [arborworkflows/ArborWebApps#129]
I loaded several files into Sponge with the pencil clicked, used them a while, then refreshed and they are gone. How do we keep files in arbor and how do we make them public

**Comment by curtislisle** [comment]
Arbor implements a default behavior where files are maintained only in the browser whe first uploaded.  This lets users drag & drop a file and run an analysis without having to save to a collection.   To keep something permanent, click the pencil and select the dataset in the bottom left spin box and click “Save to checked collection”. 
Then once you are finished, a refresh to the browser deletes all the temporary datasets that the user didn’t want to save.   It is true that sometimes temporary work is lost this way, but with a bit of discipline, nothing large is lost.  We must have just not explained it very well before.  Sorry about that.

**Comment by bobthacker** [comment]
OK, we see that now
