### ISSUE TITLE
We made output using R:object but there is no way to display it

### ISSUE THREAD

**Issue by bobthacker** [arborworkflows/ArborWebApps#131]
We changed the output type to R object, and it supposedly works, but there is no way to display an R object that we can find

**Comment by curtislisle** [comment]
There is no default way to display an arbitrary R object.  Offhand, I can’t think of anything that would work in a general case.  What I suggest is to implement an R code analysis that inputs an R object and the analysis script examines the R object and creates a data frame as output.  Dataframes can be displayed as tables,

**Comment by bobthacker** [comment]
Can we not just "cat" or "print" to a text file?

**Comment by curtislisle** [comment]
Innoway, yes. Create an analysis with a string output and you can write into that string. Strings show up as data sets in the visualization tab

**Comment by lukejharmon** [comment]
I don’t think this is working right now - see Arbor analysis “stringProblem.” A string is created but there is no way to see it in the visualizer. I can see things if they get converted to a data frame.

On May 8, 2015, at 1:43 PM, Curtis Lisle <notifications@github.com<mailto:notifications@github.com>> wrote:

Innoway, yes. Create an analysis with a string output and you can write into that string. Strings show up as data sets in the visualization tab

**Comment by curtislisle** [comment]
Agreed.   I used to use string output quite a bit, but just tested and it doesn’t work anymore. Seems to be covered some in #61 and #18.  I commented on this issue.

**Comment by bobthacker** [comment]
We need to output strings

**Comment by lukejharmon** [comment]
Hi all - I don't know if this is a related problem or not but sometimes images seem to have the same behavior - the function runs but nothing can be found in the visualization tab. Try, for example, the function in the "Arbor" collection called hclustDendrogram, using the data that I just uploaded in the same collection called anolisCophenetic.csv. The function seems to run fine - and the code runs in R - but I can't see the output on the visualization tab.

**Comment by lukejharmon** [comment]
(let me know if you think this is a new issue)

**Comment by curtislisle** [comment]
sometimes a run finishes and a conversion at the romanesco level fails to parse the output.  In these cases, I observe that an output “goes away quietly” without generating output.  I have observed “going away quietly” when trying to save dataset with bad unicode characters, etc.   It is helpful that you list the exact method which fails.  I am in a meeting today, but will be glad to investigate in the next few days.

**Comment by lukejharmon** [comment]
Just checked - I can see the plot in the "Data Management" tab and even download it (looks fine!) but it does not show up in the "visualization" tab.

**Comment by jeffbaumes** [comment]
Sorry for the latecoming to this thread. Except for the table visualization, visualizations in the visualization tab were badly broken. This is fixed now - if you still see issues reopen this issue.
