### ISSUE TITLE
On Linux Chrome, the dendrogram does not seem to be working

### ISSUE THREAD

**Issue by jeffbaumes** [arborworkflows/ArborWebApps#52]

**Comment by jeffbaumes** [comment]
Closing for now, feel free to repen @uyedaj if it is still an issue.

**Comment by uyedaj** [comment]
Missed this. No I'm still having issues, but they seem to be more widespread now...having trouble getting any visualization to work. Tested on another Ubuntu laptop and had the same errors.

Uncaught TypeError: Cannot read property 'get' of undefinedflow.
VisualizationManagementView.Backbone.View.extend.events.click .show-preset @ VisualizationManagementView.js:66
jQuery.event.dispatch @ jquery.js:5095
jQuery.event.add.elemData.handle @ jquery.js:4766

In Firefox: 
TypeError: this.visualization is undefined app.min.js:3362:16

**Comment by jeffbaumes** [comment]
This is fixed in https://github.com/Kitware/tangelohub/pull/146 and is deployed to public Arbor. Some views like dendrogram and string view now work.
