### ISSUE TITLE
table column name extraction can get confused

### ISSUE THREAD

**Issue by curtislisle** [arborworkflows/ArborWebApps#69]
Two separate wierd issues noticed with upload of slightly wierd data.

1. With the following data entered, columns are processed correctly if the file has the species names and four rows, but not with the species names and five rows (see geospiza_discrete_four and .._five) loaded in Arbor.  (note the spaces between some elements).  There are no extra lines or extra characters at the end of lines.

"species","wingL","tarsusL","culmenL","beakD","gonysW"
"magnirostris","4","3","3","3","3"
"conirostris","4","3","3","3","2"
"difficilis","4", "3", "2", "2", "2"
"scandens", "4", "3", "3", "2", "2"
"fortis","4", "3", "2", "2", "2"

![screen shot 2014-06-07 at 8 56 31 am](https://cloud.githubusercontent.com/assets/2152950/3208757/a803aad8-ee43-11e3-9628-e8e560c8fd4a.png)

2. Processing of row entries in the above dataset is inconsistent.  It seems to be related to spaces after the comma. Note that when viewing the "difficilis" row in arborweb, only some entries have quotes around them.   I think our CSV processing should be tolerant of extra spaces if possible, or we need to provide guidance about the acceptable formats. Analyses fail when I use this datafile as source data.

**Comment by jeffbaumes** [comment]
Now that we always assume column headers is this an issue?

**Comment by curtislisle** [comment]
Let's close for now and re-open only if necessary after use.
