### ISSUE TITLE
Explore adding phyloMap as external tangelo app to Arbor

### ISSUE THREAD

**Issue by curtislisle** [arborworkflows/ArborWebApps#77]
This issue tracks an exploratory effort to build off of the phyloMap prototype and integrate with Arbor's new workflow and dataset storage. The outcome of this exploration will inform us if this can become a promised / expected capability.

**Comment by jeffbaumes** [comment]
I think this is basically working - auth on non-public collections is a general problem that I think can be resolved outside this issue.
