### ISSUE TITLE
Worker exited prematurely signal 11 error

### ISSUE THREAD

**Issue by bobthacker** [arborworkflows/ArborWebApps#78]
I loaded the 12,000+ tip tree for Chloroflexi, along with the file of tags for habitats to test with Phylogenetic Signal. The input files are in the arbor section of the web app.
ChloroflexiTags1.tsv
Chloroflexi_binary_tree.newick.phy

When it runs, I receive:
Operation Failed.
Worker exited prematurely: signal 11 (SIGSEGV).

What does this error code mean?

**Comment by jeffbaumes** [comment]
These types of errors should now be handled by the supervisord process on arbor.kitware.com which should restart the worker when it fails.
