### ISSUE TITLE
New analyses / workflows do not always save to the correct collection

### ISSUE THREAD

**Issue by lukejharmon** [arborworkflows/ArborWebApps#79]
If I have two collections selected and write access to both, ArborWeb sometimes saves new analyses and workflows that I create to the wrong collection. For example, I created a new collection called PhyloCommunities. Even when I have the "edit" pen checked for that collection, new things that I make get put into the Arbor collection. The only way I have found to make things go where I want is to reboot arborweb and select only PhyloCommunities.

**Comment by jeffbaumes** [comment]
@lukejharmon please reopen if you still see this happening.
