### ISSUE TITLE
flexible tree input

### ISSUE THREAD

**Issue by lukejharmon** [arborworkflows/ArborWebApps#81]
Tree input by drag-and-drop would be better if it was either more flexible or (at least) more informative. For example, if I use Thacker's treefile - which is a newick string saved with the extension ".tre" - then arbor does not recognize it as a tree. But this outcome is not that obvious - the object appears, but can't be saved to a collection, and there is no error message.

![screen shot 2014-11-04 at 9 54 43 am](https://cloud.githubusercontent.com/assets/1669734/4904960/bcef465e-644b-11e4-8163-acebac9d9e38.png)

If I change the extension to ".phy" it works.

**Comment by jeffbaumes** [comment]
This is more informative now with #139

**Comment by jeffbaumes** [comment]
I mean Kitware/tangelohub#139
