### ISSUE TITLE
Inform user how input parameters are associated with workflow blocks.

### ISSUE THREAD

**Issue by lukejharmon** [arborworkflows/ArborWebApps#84]
We are making complex workflows, and inputs can get confusing. For example, we might have one phy tree feeding into an "acearbor" block and one phy tree feeding into a "make.treedata" block. It would be nice if the inputs for these two were labeled in some way - even: acearbor.phy, make.treedata.phy, and so on. Likewise with the outputs.

**Comment by jeffbaumes** [comment]
I think this is fixed now with showing inputs/outputs on mouse hover. Reopen if this is still an issue for you.
