### ISSUE TITLE
Unable to setup and run workflow

### ISSUE THREAD

**Issue by uyedaj** [arborworkflows/ArborWebApps#86]
On the arbor web app the workflow "coleFullWorkflow" fails to open a dialog box to setup and run. We get the following error:

Uncaught TypeError: Cannot read property 'cid' of undefined  InputsView.js:23

All of the individual pieces functions and workflows work fine, and the intermediate results seem correct.

any ideas?

**Comment by jeffbaumes** [comment]
I think we found a workaround for this a while back. @uyedaj reopen if you are still having issues.
