### ISSUE TITLE
EasyMode-AncestralState error

### ISSUE THREAD

**Issue by bobthacker** [arborworkflows/ArborWebApps#90]
This evening I got this error message:
Analysis failed. Error in constrain(ltemp, con[[i]], extra = extra) : Error parsing constraint with q12 on lhs

This was analyzing AstrophoridaNewickBinary.phy and AstrophoridaMorphologyMatrixPresentAbsent.tsv for the trait SmallStreptaster.

I will put the input files in the workflowExamples dropbox

Note, the earlier traits in the file worked: Sterrasters, GlobularSterrasters

**Comment by curtislisle** [comment]
Resolved by workaround in aceArbor to have separate continuous and discrete R processing.
