### ISSUE TITLE
Check in JSON files for easy-mode analyses in ArborWebApps and install with Ansible

### ISSUE THREAD

**Issue by jeffbaumes** [arborworkflows/ArborWebApps#94]

**Comment by curtislisle** [comment]
ansible provisoning works now, but repeat provisioning copies duplicates of analyses

**Comment by jeffbaumes** [comment]
@zackgalbreath can you look into this?

**Comment by zackgalbreath** [comment]
https://github.com/Kitware/tangelohub/pull/149 fixes the issue that Curt pointed out.

**Comment by jeffbaumes** [comment]
Closing since it appears to be solved - please repoen if the issue persists.
